URL_BASE_STATIC = 'https://static.fetchtv.com.au'
URL_BASE_APIS = 'https://apis.fetchtv.com.au/'
URL_AUTHENTICATE = f'{URL_BASE_APIS}/v3/authenticate'
URL_MESSAGES = 'wss://messages.fetchtv.com.au/v2/message/ws/messages'
URL_EPG = f'{URL_BASE_STATIC}/v2/epg/programslist'
URL_EPG_CHANNELS = f'{URL_BASE_STATIC}/v2/epg/channels'
URL_CATALOGUE = f'{URL_BASE_APIS}/v3/vod/catalogue/tab'
